In [1]:
import numpy as np

In [3]:
def check_optimal(tableau):
    column_b = -1
    for x in range(0, len(tableau[0]) - 1):
        if (tableau[0][x] < 0):
            return False

    for x in range(1, len(tableau)):
        if (tableau[x][-1] < 0):
            return False
    return True

In [4]:
def next_round_r(table):    
    m = min(table[:-1,-1])    
    if m>= 0:        
        return False    
    else:        
        return True

def next_round(table):    
    lr = len(table[:,0])   
    m = min(table[lr-1,:-1])    
    if m>=0:
        return False
    else:
        return True

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
check_optimal(np.ones((2,3)))

True

In [134]:
import cvxpy as cp

In [135]:
# Problem data.
n = 3
A = np.array([[-1,-1,-1],[2,-1,1]])
b = np.array([-2,1])

In [136]:
b

array([-2,  1])

In [137]:
A

array([[-1, -1, -1],
       [ 2, -1,  1]])

In [138]:
x = cp.Variable(n)

In [142]:
x.value = np.array([-2,6,0])

In [143]:
# Construct the problem.
# x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [0 <= x]
prob = cp.Problem(objective, constraints)

/home/abelsliver/anaconda3/lib/python3.7/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)


In [145]:
# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

[0.44444444 0.72222222 0.83333333]
[0. 0. 0.]


In [132]:
np.sum(np.array([-1,-3,-1])*x.value)

-8.096774193548388