In [1]:
# import the library pulp as p 
import pulp as p 

# Create a LP Minimization problem 
Lp_prob = p.LpProblem('Problem', p.LpMaximize) 

# Create problem Variables 
x1 = p.LpVariable("x1", lowBound = 0) # Create a variable x1 >= 0 
x2 = p.LpVariable("x2", lowBound = 0) # Create a variable x2 >= 0 
x3 = p.LpVariable("x3", lowBound = 0) # Create a variable x3 >= 0 

# Objective Function 
Lp_prob += 2*x1 - 6*x2 

# Constraints: 
Lp_prob += -x1 - x2 - x3 <= -2
Lp_prob += 2*x1 - x2 + x3 <= 1

# Display the problem 
print(Lp_prob) 

status = Lp_prob.solve() # Solver 
print(p.LpStatus[status]) # The solution status 

# Printing the final solution 
print(p.value(x1), p.value(x2), p.value(x3), p.value(Lp_prob.objective)) 

Problem:
MAXIMIZE
2*x1 + -6*x2 + 0
SUBJECT TO
_C1: - x1 - x2 - x3 <= -2

_C2: 2 x1 - x2 + x3 <= 1

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous

Optimal
0.0 0.5 1.5 -3.0


In [2]:
# import the library pulp as p 
import pulp as p 

# Create a LP Minimization problem 
Lp_prob = p.LpProblem('Problem', p.LpMaximize) 

# Create problem Variables 
x1 = p.LpVariable("x1", lowBound = 0) # Create a variable x1 >= 0 
x2 = p.LpVariable("x2", lowBound = 0) # Create a variable x2 >= 0 

# Objective Function 
Lp_prob += x1 - 3*x2

# Constraints: 
Lp_prob += -x1 - x2 <= -3
Lp_prob += -x1 + x2 <= -1
Lp_prob += x1 + 2*x2 <= 2

# Display the problem 
print(Lp_prob) 

status = Lp_prob.solve() # Solver 
print(p.LpStatus[status]) # The solution status 

# Printing the final solution 
print(p.value(x1), p.value(x2), p.value(x3), p.value(Lp_prob.objective)) 

Problem:
MAXIMIZE
1*x1 + -3*x2 + 0
SUBJECT TO
_C1: - x1 - x2 <= -3

_C2: - x1 + x2 <= -1

_C3: x1 + 2 x2 <= 2

VARIABLES
x1 Continuous
x2 Continuous

Infeasible
3.0 0.0 1.5 3.0


In [3]:
# import the library pulp as p 
import pulp as p 

# Create a LP Minimization problem 
Lp_prob = p.LpProblem('Problem', p.LpMaximize) 

# Create problem Variables 
x1 = p.LpVariable("x1", lowBound = 0) # Create a variable x1 >= 0 
x2 = p.LpVariable("x2", lowBound = 0) # Create a variable x2 >= 0 

# Objective Function 
Lp_prob += x1 - 3*x2

# Constraints: 
Lp_prob += -x1 - x2 <= -3
Lp_prob += -x1 + x2 <= -1
Lp_prob += -x1 + 2*x2 <= 2

# Display the problem 
print(Lp_prob) 

status = Lp_prob.solve() # Solver 
print(p.LpStatus[status]) # The solution status 

# Printing the final solution 
print(p.value(x1), p.value(x2), p.value(x3), p.value(Lp_prob.objective)) 

Problem:
MAXIMIZE
1*x1 + -3*x2 + 0
SUBJECT TO
_C1: - x1 - x2 <= -3

_C2: - x1 + x2 <= -1

_C3: - x1 + 2 x2 <= 2

VARIABLES
x1 Continuous
x2 Continuous

Unbounded
0.0 0.0 1.5 0.0


In [1]:
from simplex_method import Simplex_method
import numpy as np

In [2]:

# inputs 

# A will contain the coefficients of the constraints 
A = np.array([[-1,-1, 1, 0, 0],
              [-1, 1, 0, 1, 0],
              [-1, 2, 0, 0, 1]])

# b will contain the amount of resources 
b = np.array([-3, -1, 2])

# c will contain coefficients of objective function Z 
c = np.array([1, -3, 0, 0, 0])

simplex = Simplex_method(A,b,c)

print(simplex.solve(verbor=True))

dual feasible
Start convert negative components
run dual simplex method
Phase one
Objective
 [[ 0  3 -3 -1  2]]
Dictionary
 [[ 2 -3 -1 -1  1  0  0]
 [ 3 -1 -1  1  0  1  0]
 [ 4  2 -1  2  0  0  1]]
iter: 1
Dictionary
 [[ 0.  3.  1. -1. -1.  0.  0.]
 [ 3.  2.  0.  1. -1.  1.  0.]
 [ 4.  5.  0.  2. -1.  0.  1.]]
optimal: 3.0
Phase two
Objective
 [[0. 3. 3. 2. 5.]]
Dictionary
 [[ 0.  3.  1. -1. -1.  0.  0.]
 [ 3.  2.  0.  1. -1.  1.  0.]
 [ 4.  5.  0.  2. -1.  0.  1.]]
{'iter': 1, 'optimal': 3.0, 'sol': array([3., 0., 0., 2., 5.])}


/home/abelsliver/Project/MAO/simplex_method_for_linear_program/project/simplex_method/simplex_method.py:126: RuntimeWarning: divide by zero encountered in true_divide
  s = np.max(delta_zn/self.zn)**-1
/home/abelsliver/Project/MAO/simplex_method_for_linear_program/project/simplex_method/simplex_method.py:128: RuntimeWarning: divide by zero encountered in true_divide
  j = np.argmax(delta_zn/self.zn)
